### ISSUE TITLE
Server crash with 1.3.2

### ISSUE THREAD

**Issue by mxnmnm** [MehVahdJukaar/sawmill#18]
The server does not startup with this version :( 

Here is the log: https://gist.github.com/mxnmnm/57624b4eaeccaac9c870e9f80f3174eb

**Comment by MehVahdJukaar** [comment]
is your forge updated?

**Comment by mxnmnm** [comment]
This happens on the latest neoforge as well (normal forge crashes for me because of other mods not sure which ones tho)

**Comment by MehVahdJukaar** [comment]
Well that issue is specifically something that was fixed in forge 47.1.40 or something like so. It was also later fixed in neoforge but it's completely a loader issue

**Comment by mxnmnm** [comment]
https://gist.github.com/mxnmnm/9f1f0872fa3a24d0b1b6c0f5b8dec32a

**Comment by mxnmnm** [comment]
still happens on the latest neoforge :/

**Comment by MehVahdJukaar** [comment]
Then report to neoforge. It's them loading a client side class unsafely. Or just use forge

**Comment by MehVahdJukaar** [comment]
I know for a fact that that issue was fixed in nei 1.20.4

**Comment by unilock** [comment]
This is the relevant PR to NeoForge 1.20.4: https://github.com/neoforged/NeoForge/pull/541

Here's hoping they backport it to 1.20.1.

**Comment by NeuTraLZero** [comment]
Having a similar problem in Singleplayer. The world won't load the first time the game's launched and will prompt to use Safe Mode, but after the second try the world would load fine for some reason

I tested with both Forge 47.2.6 and 47.2.19 and this still happens

**Comment by MehVahdJukaar** [comment]
send latest.log

**Comment by MehVahdJukaar** [comment]
also the recipe sort config will disable sorting hence also disabling this stuff

**Comment by NeuTraLZero** [comment]
Here's the log up until the safe mode warning

[latest.log](https://github.com/MehVahdJukaar/sawmill/files/14280025/latest.log)

**Comment by MehVahdJukaar** [comment]
Your issue comes from this mod
TRANSFORMER/majruszsdifficulty@1.9.8/com.majruszsdifficulty.
Their issue not mine

**Comment by NeuTraLZero** [comment]
Yeah but I already tried disabling both Majrusz's Library and Difficulty and it's still happening

Disabling just Sawmill let me enter my world normally every time so I don't see why it wouldn't be a Sawmill problem

[latest.log](https://github.com/MehVahdJukaar/sawmill/files/14280647/latest.log)

**Comment by MehVahdJukaar** [comment]
And now issue is from framework/backpacked. Their issue too. They all need to make their tab code server safe

**Comment by NeuTraLZero** [comment]
1.3.3 seem to have fixed both these issues? Need more confirmation

**Comment by MehVahdJukaar** [comment]
oh good. still those mods shouldnt have failed when merely refreshing tags after tag load
